function yamlConfigMap(namespace, dockerUrl) {
	return `apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: ${namespace}
data:
  DATA_STACK_ALLOWED_FILE_TYPE: ${d.i("formElement_DATA_STACK_ALLOWED_FILE_TYPE").value}
  API_LOGS_METHODS: ${d.i("formElement_API_LOGS_METHODS").value}
  API_LOGS_TTL_DAYS: ${d.i("formElement_API_LOGS_TTL_DAYS").value}
  API_REQUEST_TIMEOUT: ${d.i("formElement_API_REQUEST_TIMEOUT").value}
  BOOKMARK_OPEN_TAB: ${d.i("formElement_BOOKMARK_OPEN_TAB").value}
  CACHE_CLUSTER: ${d.i("formElement_CACHE_CLUSTER").value}
  CACHE_HOST: ${d.i("formElement_CACHE_HOST").value}
  CACHE_PORT: ${d.i("formElement_CACHE_PORT").value}
  CACHE_RECONN_ATTEMPTS: ${d.i("formElement_CACHE_RECONN_ATTEMPTS").value}
  CACHE_RECONN_TIMEWAIT_MILLI: ${d.i("formElement_CACHE_RECONN_TIMEWAIT_MILLI").value}
  CERTIFICATE_COMMON_NAME: ${d.i("formElement_CERTIFICATE_COMMON_NAME").value}
  CERTIFICATE_COUNTRY: ${d.i("formElement_CERTIFICATE_COUNTRY").value}
  CERTIFICATE_EMAIL: ${d.i("formElement_CERTIFICATE_EMAIL").value}
  CERTIFICATE_LOCALITY: ${d.i("formElement_CERTIFICATE_LOCALITY").value}
  CERTIFICATE_ORGANIZATION: ${d.i("formElement_CERTIFICATE_ORGANIZATION").value}
  CERTIFICATE_ORGANIZATION_UNIT: ${d.i("formElement_CERTIFICATE_ORGANIZATION_UNIT").value}
  CERTIFICATE_ROOT_DOMAIN: ${d.i("formElement_CERTIFICATE_ROOT_DOMAIN").value}
  CERTIFICATE_STATE: ${d.i("formElement_CERTIFICATE_STATE").value}
  DATA_STACK_NAMESPACE: ${d.i("formElement_DATA_STACK_NAMESPACE").value}
  DIRECTORY_CONNECTION_TIMEOUT_MILLI: ${d.i("formElement_DIRECTORY_CONNECTION_TIMEOUT_MILLI").value}
  DIRECTORY_RECORD_FETCH_TIME_LIMIT: ${d.i("formElement_DIRECTORY_RECORD_FETCH_TIME_LIMIT").value}
  DOCKER_CONTAINER_ENGINE: ${d.i("formElement_DOCKER_CONTAINER_ENGINE").value}
  DOCKER_CONTAINER_ENGINE_TLS_VERIFY: ${d.i("formElement_DOCKER_CONTAINER_ENGINE_TLS_VERIFY").value}
  DOCKER_CONTAINER_FORMAT: ${d.i("formElement_DOCKER_CONTAINER_FORMAT").value}
  DOCKER_REGISTRY_SERVER: ${d.i("formElement_DOCKER_REGISTRY_SERVER").value}
  DOCKER_REGISTRY_TYPE: ${d.i("formElement_DOCKER_REGISTRY_TYPE").value}
  DS_FS_MOUNT_PATH: ${d.i("formElement_DS_FS_MOUNT_PATH").value}
  ENCRYPTION_KEY: ${d.i("formElement_ENCRYPTION_KEY").value}
  FAAS_LOGS_TTL_DAYS: ${d.i("formElement_FAAS_LOGS_TTL_DAYS").value}
  FQDN: ${d.i("formElement_FQDN").value}
  GOOGLE_API_KEY: ${d.i("formElement_GOOGLE_API_KEY").value}
  HOOK_CONNECTION_TIMEOUT: ${d.i("formElement_HOOK_CONNECTION_TIMEOUT").value}
  HOOK_POST_BATCH: ${d.i("formElement_HOOK_POST_BATCH").value}
  HOOK_RETRY: ${d.i("formElement_HOOK_RETRY").value}
  KEY_SIZE: ${d.i("formElement_KEY_SIZE").value}
  LOG_LEVEL: ${d.i("formElement_LOG_LEVEL").value}
  MAX_FILE_SIZE: ${d.i("formElement_MAX_FILE_SIZE").value}
  MAX_JSON_SIZE: ${d.i("formElement_MAX_JSON_SIZE").value}
  MODE: ${d.i("formElement_MODE").value}
  MONGO_APPCENTER_URL: ${d.i("formElement_MONGO_APPCENTER_URL").value}
  MONGO_AUTHOR_DBNAME: ${d.i("formElement_MONGO_AUTHOR_DBNAME").value}
  MONGO_AUTHOR_URL: ${d.i("formElement_MONGO_AUTHOR_URL").value}
  MONGO_CONNECTION_POOL_SIZE: ${d.i("formElement_MONGO_CONNECTION_POOL_SIZE").value}
  MONGO_LOGS_DBNAME: ${d.i("formElement_MONGO_LOGS_DBNAME").value}
  MONGO_LOGS_URL: ${d.i("formElement_MONGO_LOGS_URL").value}
  MONGO_RECONN_TIME_MILLI: ${d.i("formElement_MONGO_RECONN_TIME_MILLI").value}
  MONGO_RECONN_TRIES: ${d.i("formElement_MONGO_RECONN_TRIES").value}
  NE_EVENTS_URL: ${d.i("formElement_NE_EVENTS_URL").value}
  NODE_MAX_HEAP_SIZE: ${d.i("formElement_NODE_MAX_HEAP_SIZE").value}
  PROXY_ENABLE_TLS: ${d.i("formElement_PROXY_ENABLE_TLS").value}
  RBAC_BOT_TOKEN_DURATION: ${d.i("formElement_RBAC_BOT_TOKEN_DURATION").value}
  RBAC_HB_INTERVAL: ${d.i("formElement_RBAC_HB_INTERVAL").value}
  RBAC_HB_MISS_COUNT: ${d.i("formElement_RBAC_HB_MISS_COUNT").value}
  RBAC_PASSWORD_COMPLEXITY: ${d.i("formElement_RBAC_PASSWORD_COMPLEXITY").value}
  RBAC_PASSWORD_LENGTH: ${d.i("formElement_RBAC_PASSWORD_LENGTH").value}
  RBAC_USER_AUTH_MODES: ${d.i("formElement_RBAC_USER_AUTH_MODES").value}
  RBAC_USER_CLOSE_WINDOW_TO_LOGOUT: ${d.i("formElement_RBAC_USER_CLOSE_WINDOW_TO_LOGOUT").value}
  RBAC_USER_LOGIN_FAILURE_COOLDOWN: ${d.i("formElement_RBAC_USER_LOGIN_FAILURE_COOLDOWN").value}
  RBAC_USER_LOGIN_FAILURE_DURATION: ${d.i("formElement_RBAC_USER_LOGIN_FAILURE_DURATION").value}
  RBAC_USER_LOGIN_FAILURE_THRESHOLD: ${d.i("formElement_RBAC_USER_LOGIN_FAILURE_THRESHOLD").value}
  RBAC_USER_RELOGIN_ACTION: ${d.i("formElement_RBAC_USER_RELOGIN_ACTION").value}
  RBAC_USER_TO_SINGLE_SESSION: ${d.i("formElement_RBAC_USER_TO_SINGLE_SESSION").value}
  RBAC_USER_TOKEN_DURATION: ${d.i("formElement_RBAC_USER_TOKEN_DURATION").value}
  RBAC_USER_TOKEN_REFRESH: ${d.i("formElement_RBAC_USER_TOKEN_REFRESH").value}
  RELEASE: ${release}
  SAVE_FILTER_DEFAULT_MODE_PRIVATE: ${d.i("formElement_SAVE_FILTER_DEFAULT_MODE_PRIVATE").value}
  SEC_HEADER_ACCESS_CONTROL_ALLOW_HEADERS: ${d.i("formElement_SEC_HEADER_ACCESS_CONTROL_ALLOW_HEADERS").value}
  SEC_HEADER_ACCESS_CONTROL_ALLOW_METHODS: ${d.i("formElement_SEC_HEADER_ACCESS_CONTROL_ALLOW_METHODS").value}
  SEC_HEADER_ACCESS_CONTROL_ALLOW_ORIGIN: ${d.i("formElement_SEC_HEADER_ACCESS_CONTROL_ALLOW_ORIGIN").value}
  SEC_HEADER_CACHE_CONTROL: ${d.i("formElement_SEC_HEADER_CACHE_CONTROL").value}
  SEC_HEADER_CONTENT_SECURITY_POLICY: ${d.i("formElement_SEC_HEADER_CONTENT_SECURITY_POLICY").value}
  SEC_HEADER_SERVER: ${d.i("formElement_SEC_HEADER_SERVER").value}
  SEC_HEADER_STRICT_TRANSPORT_SECURITY: ${d.i("formElement_SEC_HEADER_STRICT_TRANSPORT_SECURITY").value}
  SEC_HEADER_X_CONTENT_TYPE_OPTION: ${d.i("formElement_SEC_HEADER_X_CONTENT_TYPE_OPTION").value}
  SEC_HEADER_X_FRAME_OPTION: ${d.i("formElement_SEC_HEADER_X_FRAME_OPTION").value}
  SEC_HEADER_X_POWERED_BY: ${d.i("formElement_SEC_HEADER_X_POWERED_BY").value}
  SEC_HEADER_X_XSS_PROTECTION: ${d.i("formElement_SEC_HEADER_X_XSS_PROTECTION").value}
  STREAMING_CHANNEL: ${d.i("formElement_STREAMING_CHANNEL").value}
  STREAMING_HOST: ${d.i("formElement_STREAMING_HOST").value}
  STREAMING_PASS: ${d.i("formElement_STREAMING_PASS").value}
  STREAMING_RECONN_ATTEMPTS: ${d.i("formElement_STREAMING_RECONN_ATTEMPTS").value}
  STREAMING_RECONN_TIMEWAIT_MILLI: ${d.i("formElement_STREAMING_RECONN_TIMEWAIT_MILLI").value}
  STREAMING_USER: ${d.i("formElement_STREAMING_USER").value}
  TLS_REJECT_UNAUTHORIZED: ${d.i("formElement_TLS_REJECT_UNAUTHORIZED").value}
  TZ_DEFAULT: ${d.i("formElement_TZ_DEFAULT").value}
  UI_LOGS_TTL: ${d.i("formElement_UI_LOGS_TTL").value}
 `
}